---

- name: provision the admin host
  hosts: admin
  become: yes

  vars:
    hosts_file_entries:
      - { ip: '172.16.1.110', entry: 'trusty32-1 trusty32-1.vagrant.dev'}
      - { ip: '172.16.1.120', entry: 'trusty32-2 trusty32-2.vagrant.dev'}
      - { ip: '172.16.1.130', entry: 'trusty32-3 trusty32-3.vagrant.dev'}
      - { ip: '172.16.1.140', entry: 'trusty32-4 trusty32-4.vagrant.dev'}
      - { ip: '172.16.1.150', entry: 'trusty32-5 trusty32-5.vagrant.dev'}
      - { ip: '172.16.1.160', entry: 'trusty32-6 trusty32-6.vagrant.dev'}
      - { ip: '172.16.1.170', entry: 'trusty32-7 trusty32-7.vagrant.dev'}
      - { ip: '172.16.1.180', entry: 'trusty32-8 trusty32-8.vagrant.dev'}
      - { ip: '172.16.1.190', entry: 'trusty32-9 trusty32-9.vagrant.dev'}

      - { ip: '172.16.2.110', entry: 'trusty64-1 trusty64-1.vagrant.dev'}
      - { ip: '172.16.2.120', entry: 'trusty64-2 trusty64-2.vagrant.dev'}
      - { ip: '172.16.2.130', entry: 'trusty64-3 trusty64-3.vagrant.dev'}
      - { ip: '172.16.2.140', entry: 'trusty64-4 trusty64-4.vagrant.dev'}
      - { ip: '172.16.2.150', entry: 'trusty64-5 trusty64-5.vagrant.dev'}
      - { ip: '172.16.2.160', entry: 'trusty64-6 trusty64-6.vagrant.dev'}
      - { ip: '172.16.2.170', entry: 'trusty64-7 trusty64-7.vagrant.dev'}
      - { ip: '172.16.2.180', entry: 'trusty64-8 trusty64-8.vagrant.dev'}
      - { ip: '172.16.2.190', entry: 'trusty64-9 trusty64-9.vagrant.dev'}

  tasks:
    - name: copy the vagrant user files
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: 'vagrant'
        group: 'vagrant'
        mode: '{{ item.perms }}'
      with_items:
        - src: 'files/bash-profile.sh'
          dest: '/home/vagrant/.bash_profile'
          perms: '0640'
        - src: 'files/ssh-config.txt'
          dest: '/home/vagrant/.ssh/config'
          perms: '0640'

    - name: copy the system-wide files
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: 'root'
        group: 'root'
        mode: '{{ item.perms }}'
      with_items:
        - src: 'files/admin-host-aliases.sh'
          dest: '/etc/profile.d/Z90-aliases.sh'
          perms: '0644'

    - name: create symlinks for the vagrant user
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: 'vagrant'
        group: 'vagrant'
        force: yes
        state: link
      with_items:
        - src: '/vagrant/commands'
          dest: '~vagrant/commands'
        - src: '/vagrant/ansible'
          dest: '~vagrant/ansible'

    - name: make sure vault password file exists
      file:
        path: '/vagrant/ansible/.vault.pass'
        mode: '0600'
        owner: 'vagrant'
        group: 'vagrant'
        state: touch

    - name: add the pre-configured vagrant instances to the hosts file
      lineinfile:
        dest: '/etc/hosts'
        regexp: '^{{ item.ip }}'
        line: '{{ item.ip }} {{ item.entry }}'
        state: present
      with_items: '{{ hosts_file_entries }}'


- include: os-packages.yml
  vars:
    hosts: 'admin'


- name: harden the server
  hosts: admin
  become: yes

  roles:
    - role: dev-sec.os-hardening

